name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3.5.0
        with:
          go-version: '1.20'
      - name: Display go version
        run: go version
      - name: Check if difference
        uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
            .github/workflows/test.yml
      - name: Build
        run: make build
        if: env.GIT_DIFF
      - name: Test
        run: make test
        if: env.GIT_DIFF
      - name: Test race
        run: make test-race
        if: env.GIT_DIFF
      - name: Test integration
        run: make test-cli
        if: env.GIT_DIFF

  test-cover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3.5.0
        with:
          go-version: '1.20'
      - name: Display go version
        run: go version
      - name: Check if difference
        uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
            .github/workflows/test.yml
      - name: Build
        run: make build
        if: env.GIT_DIFF
      - name: Test & Coverage repoting
        run: make test-cover
        if: env.GIT_DIFF
      - name: Upload coverage report
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
        if: env.GIT_DIFF

  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3.5.0
        with:
          go-version: '1.20'
      - name: Display go version
        run: go version
      - name: Check if difference
        uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
            .github/workflows/test.yml
      - name: Benchmarks for gas calculations
        run: |
          cd ./x/wasm/keeper
          go test -bench .
        if: env.GIT_DIFF
      - name: Benchmarks to compare with native modules
        run: |
          cd ./benchmarks
          go test -bench .
        if: env.GIT_DIFF
